export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const UPDATE_PRODUCT_PAGE = 'UPDATE_PRODUCT_PAGE';
export const UPDATE_CHECKOUT_CONFIRMATION_INFO = 'UPDATE_CHECKOUT_CONFIRMATION_INFO'